---
title: 'Topograph Analysis: Gamma Stats'
author: "Carter Daniels"
date: "`r Sys.Date()`"
output: html_document
---

```{r}

wd_path <- "E:/Dropbox/2 All of Carter's Stuff/Carter Local/Jupyter Lab"
setwd(wd_path)

library(BayesFactor)
```

```{r}

#load and prep data
data <- read.csv("topography_gamma.csv")
data$Schedule<-factor(data$Schedule,levels=c("DRL","FMI"))
data$Motivation<-factor(data$Motivation,levels=c("B","PF"))
data$Interval<-factor(data$Interval,levels=c("3","6"))
data$InitRsp<-factor(data$InitRsp,levels=c("NPM","LPM"))

```

# 1.1 Analysis of Gamma Mean 

```{r}
bayesRM_mu <- anovaBF(lnValue~Interval*Motivation*InitRsp*Schedule,data=data[which(data$variable=="mu"),],whichRandom="mouseID")
bayesRM_mu
```

```{r, fig.width = 36, fig.height = 36}
plot(bayesRM_mu)

```

# 1.2 Interaction Probes


```{r}
bayesRM_mu_DRL <- anovaBF(lnValue~Motivation,data=data[which(data$variable=="mu" & data$Schedule=="DRL"),],whichRandom="mouseID")
bayesRM_mu_DRL
plot(bayesRM_mu_DRL)
```

```{r}
bayesRM_mu_FMI <- anovaBF(lnValue~Motivation,data=data[which(data$variable=="mu" & data$Schedule=="FMI"),],whichRandom="mouseID")
bayesRM_mu_FMI
plot(bayesRM_mu_FMI)
```


# 2. Analysis of Gamma SD 

```{r}
bayesRM_sd <- anovaBF(lnValue~Interval*Motivation*InitRsp*Schedule,data=data[which(data$variable=="sd"),],whichRandom="mouseID")
bayesRM_sd
```

```{r, fig.width = 36, fig.height = 36}
plot(bayesRM_sd)

```

# 3. Analysis of Gamma CV 

```{r}
bayesRM_cv <- anovaBF(lnValue~Interval*Motivation*InitRsp*Schedule,data=data[which(data$variable=="cv"),],whichRandom="mouseID")
bayesRM_cv
```

```{r, fig.width = 36, fig.height = 36}
plot(bayesRM_cv)

```